You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
  
  //SOLUTION :-
  class Solution {
    public char findTheDifference(String s, String t) {
        int n = s.length();
        char c = t.charAt(n);
        for(int i = 0; i< n; i++){
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }
}
  
